name: Test Github Action
author: ahsayde
description: 'test github actions'
inputs:
  webhook:
    description: magalix guard webhook
    required: true
  
  directory:
    description: root directory
    default: '.'
    required: false

  repo:
    default: ${{ github.repository }}
  
  branch:
    default: ${{ github.ref }}
  
  commit:
    default: ${{ github.sha }}

  gh-token:
    default: ${{ github.token }}

  gh-checkrun-report:
    description: create check-run to show result summary 
    default: true

  gh-code-scanning:
    description: enable github code scanning
    default: true

branding:
  icon: shield
  color: purple

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --webhook
    - ${{ inputs.webhook }}
    - --directory
    - ${{ inputs.directory }}
    - --repo
    - ${{ inputs.repo }}
    - --branch
    - ${{ inputs.branch }}
    - --commit
    - ${{ inputs.commit }}
    - --gh-token
    - ${{ inputs.gh-token }}
    - --gh-code-scanning
    - ${{ inputs.gh-code-scanning }}
    - --gh-checkrun-report
    - ${{ inputs.gh-checkrun-report }}
