name: Test Github Action
author: ahsayde
description: 'test github actions'
inputs:
  directory:
    description: file path
    default: '.'
    required: false

branding:
  icon: 'shield'
  color: 'purple'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.directory }}
